// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SynthetIQ.DbContext.Models;

public partial class Assistant
{
    public int AssistantId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int ModelId { get; set; }

    public DateTime CreatedDt { get; set; }

    public DateTime? ModifiedDt { get; set; }

    public virtual ICollection<Llmconfiguration> Llmconfigurations { get; set; } = new List<Llmconfiguration>();

    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();

    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
}