// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SynthetIQ.DbContext.Models;

public partial class Exception
{
    public int ExceptionId { get; set; }

    public int? UserId { get; set; }

    public string ExceptionMessage { get; set; }

    public string StackTrace { get; set; }

    public DateTime ExceptionDate { get; set; }

    public string Source { get; set; }

    public virtual User User { get; set; }
}