// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;

using SynthetIQ.DbContext.Models;
using SynthetIQ.DbContext.Models.Configurations;
using System;
using System.Collections.Generic;
#nullable disable

namespace SynthetIQ.DbContext.Context;

public partial class SynthetIQContext : Microsoft.EntityFrameworkCore.DbContext
{
    public SynthetIQContext(DbContextOptions<SynthetIQContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Assistant> Assistants { get; set; }

    public virtual DbSet<Exception> Exceptions { get; set; }

    public virtual DbSet<Llmconfiguration> Llmconfigurations { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<Tag> Tags { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.AssistantConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ExceptionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LlmconfigurationConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProjectConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TagConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UserConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
