// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SynthetIQ.DbContext.Models;
using System;
using System.Collections.Generic;

namespace SynthetIQ.DbContext.Models.Configurations
{
    public partial class AssistantConfiguration : IEntityTypeConfiguration<Assistant>
    {
        public void Configure(EntityTypeBuilder<Assistant> entity)
        {
            entity.HasKey(e => e.AssistantId).HasName("PK__Assistan__3756F7504B6F2B21");

            entity.Property(e => e.AssistantId).HasColumnName("AssistantID");
            entity.Property(e => e.CreatedDt)
            .HasDefaultValueSql("(getdate())")
            .HasColumnType("datetime");
            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.ModifiedDt).HasColumnType("datetime");
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(255);

            entity.HasMany(d => d.Tags).WithMany(p => p.Assistants)
            .UsingEntity<Dictionary<string, object>>(
                "AssistantTag",
                r => r.HasOne<Tag>().WithMany()
                    .HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Assistant__TagID__46E78A0C"),
                l => l.HasOne<Assistant>().WithMany()
                    .HasForeignKey("AssistantId")
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Assistant__Assis__45F365D3"),
                j =>
                {
                    j.HasKey("AssistantId", "TagId");
                    j.ToTable("AssistantTags");
                    j.IndexerProperty<int>("AssistantId").HasColumnName("AssistantID");
                    j.IndexerProperty<int>("TagId").HasColumnName("TagID");
                });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Assistant> entity);
    }
}
