// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SynthetIQ.DbContext.Models;
using System;
using System.Collections.Generic;

namespace SynthetIQ.DbContext.Models.Configurations
{
    public partial class ExceptionConfiguration : IEntityTypeConfiguration<Exception>
    {
        public void Configure(EntityTypeBuilder<Exception> entity)
        {
            entity.HasKey(e => e.ExceptionId).HasName("PK__Exceptio__26981DA820A1EEC0");

            entity.Property(e => e.ExceptionId).HasColumnName("ExceptionID");
            entity.Property(e => e.ExceptionDate)
            .HasDefaultValueSql("(getdate())")
            .HasColumnType("datetime");
            entity.Property(e => e.ExceptionMessage).IsRequired();
            entity.Property(e => e.Source).HasMaxLength(255);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.Exceptions)
            .HasForeignKey(d => d.UserId)
            .HasConstraintName("FK__Exception__UserI__52593CB8");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Exception> entity);
    }
}
