// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SynthetIQ.DbContext.Models;
using System;
using System.Collections.Generic;

namespace SynthetIQ.DbContext.Models.Configurations
{
    public partial class LlmconfigurationConfiguration : IEntityTypeConfiguration<Llmconfiguration>
    {
        public void Configure(EntityTypeBuilder<Llmconfiguration> entity)
        {
            entity.HasKey(e => e.LlmconfigurationId).HasName("PK__LLMConfi__66990F00EFEFB4B7");

            entity.ToTable("LLMConfigurations");

            entity.Property(e => e.LlmconfigurationId).HasColumnName("LLMConfigurationID");
            entity.Property(e => e.Apikey)
            .IsRequired()
            .HasMaxLength(255)
            .HasColumnName("APIKey");
            entity.Property(e => e.Apiurl)
            .IsRequired()
            .HasMaxLength(255)
            .HasColumnName("APIUrl");
            entity.Property(e => e.AssistantId).HasColumnName("AssistantID");
            entity.Property(e => e.Endpoints).IsRequired();
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(255);

            entity.HasOne(d => d.Assistant).WithMany(p => p.Llmconfigurations)
            .HasForeignKey(d => d.AssistantId)
            .HasConstraintName("FK__LLMConfig__Assis__3C69FB99");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Llmconfiguration> entity);
    }
}
